/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { W3bucketAbi } from "./W3bucketAbi";
export * as factories from "./factories";
export { W3bucketAbi__factory } from "./factories/W3bucketAbi__factory";
