name: Beta Deploy

on:
  push:
    branches: [ main ]

jobs:
  beta-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Setup Node v18
        uses: actions/setup-node@v1
        with:
          node-version: v18.16.0

      - uses: actions/cache@v3
        with:
          path: |
            .next
            .yarn/cache
            ./node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn export

      - name: Deploy Gh-Pages 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          cname: beta.crustcloud.io